### ISSUE TITLE
CNN program

### ISSUE THREAD

**Issue by Dove96** [Dove96/Python#1]
classifier.fit_generator(training_set,
                         steps_per_epoch = 8000,
                         nb_epoch = 2,
                         validation_data = test_set,
                         val_samples = 2000)
__main__:5: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
__main__:5: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras.pre..., steps_per_epoch=8000, validation_data=<keras.pre..., steps=2000, epochs=2)`
Traceback (most recent call last):

  File "<ipython-input-11-cb98b7c74e13>", line 5, in <module>
    val_samples = 2000)

  File "C:\Users\Prisilla\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)

TypeError: fit_generator() got an unexpected keyword argument 'steps'

**Comment by Dove96** [comment]
Can i know why i am getting this error (warnings). I am working on python 3.6 on windows 7 (64-bit).
this code i am running on spyder using anaconda3.
From Anaconda prompt > conda list displays as follows
[doc.docx](https://github.com/Dove96/Python/files/1589611/doc.docx)
